### PR TITLE
Allow laravel 10

### PR DESCRIPTION
**Pull request by it-can**

### CODE REVIEW

**Comment by it-can** [comment]
@LaravelFreelancerNL

**Comment by LaravelFreelancerNL** [comment]
I've added L10 to the test suite. However log-fake doesn't support L10 yet. So, as soon as that dependency complies we should be able to merge this pr.

**Comment by it-can** [comment]
added a PR  https://github.com/timacdonald/log-fake/pull/42

**Comment by it-can** [comment]
@LaravelFreelancerNL ok fixed in https://github.com/timacdonald/log-fake/releases/tag/2.1.0

**Comment by LaravelFreelancerNL** [comment]
Excellent. Thanks for the assist.

**Pull request merged**
